### ISSUE TITLE
Accessing statistics during simulation

### ISSUE THREAD

**Issue by adityamdeshpande** [sstsimulator/sst-elements#1052]
@nmhamster: @gvoskuilen : Is there a way to access statistics during simulation inside a component. I wanted to access different statistics within Ariel/memHierarchy component during the simulation?

**Comment by gvoskuilen** [comment]
@adityamdeshpande How did you want to access them? Just dump them during/throughput the simulation or actually read them in the code? If you just want to dump statistics, you can configure statistics in the python input file to get written at a regular cadence (e.g., every 10us), and there's an ariel api call 'ariel_output_stats()' that you can use to trigger a statistic dump from ariel's executable.

**Comment by adityamdeshpande** [comment]
@gvoskuilen I was looking at accessing them and read them in the code to trigger some additional action.

**Comment by gvoskuilen** [comment]
@adityamdeshpande It will be lower overhead and simpler just to keep a duplicate local counter that tracks the statistic rather than call into the core to check the statistic value. There's no accessor interface for data values since statistics were designed to be configurable to track data in different ways. Therefore, accessing the data from a component would require type-checking the statistic, and even then, not all types have public accessors for the data values.
