### ISSUE TITLE
cycle count for Ariel

### ISSUE THREAD

**Issue by Xiaoyang-Lu** [sstsimulator/sst-elements#1094]
I found that when I executed the same application with same configuration many times, the Statistic output of Ariel cycle count every time I got is different. I want to know it this correct? Why?

**Comment by gvoskuilen** [comment]
Ariel is not cycle-reproducible because of some non-determinism in the interaction between the natively-running binary, Pin, and SST. For example there is some variation in when the Pintool initially starts sending instructions to Ariel. Simulating a multi-threaded application will also add non-determinism. However, the cycle counts should be similar between executions, especially longer running ones, and so we use the average time across multiple runs.
