### ISSUE TITLE
[Help Wanted] Merlin, Dragonfly, adaptive-local routing: Is output_credits[ ] get updated?

### ISSUE THREAD

**Issue by yao-kang** [sstsimulator/sst-elements#1468]
Hello,

I have been studying SST Dragonfly adaptive routing in *dragonfly.cc* file and find that using minimal routing and adaptive routing gives the same results.
I trigger different routing algorithms by setting following in merlin/tests/dragon_72_test.py
> sst.merlin._params["dragonfly:algorithm"] = "minimal"
   Or
> sst.merlin._params["dragonfly:algorithm"] = "adaptive-local"
> sst.merlin._params["dragonfly:adaptive_threshold"] = "2.0"

My current understanding is that adaptive routing is done in 
**void topo_dragonfly::reroute()** 
by comparing the credit value of a direct route and a valiant route. 
These credit values are stored in the **output_credits[ ]** array, however it seems that this array is never updated after its first initialization. 

- I would like to know if I am missing something in order to use adaptive routing correctly?
- An additional question is why choosing credit value instead of queue length for adaptive routing decision?

Thank you

**Comment by feldergast** [comment]
You are correct that the adaptive routing happens on reroute().  The output_credits array in the topology object is set to point to the array in the router that instanced the topology object.  The values are updated and used by the router and the topology class just has a view of that state, but can't update it itself.  The router also gives a pointer to the queue length arrays it keeps updated.  The hyperX uses the queue length array instead of the credit array.

In the dragonfly model, I was playing with other methods for making routing decisions.  I've been working on a new version of the adaptive routing algorithm that uses queue lengths, but it is not in the devel branch.  I'm not sure if this will make it into the 10.0 release or not, but will for sure be in shortly afterwards.

Without knowing what your communication pattern looks like, I don't know why you see the same results with the two algorithms.  This can happen for communication patterns that don't stress the bandwidth of the network (for example, small allreduce operations).  If you set the algorithm to adaptive-local the way indicated, it should have enabled it.
