### ISSUE TITLE
Measure Link Utilization (Merlin)

### ISSUE THREAD

**Issue by tommasobo** [sstsimulator/sst-elements#1722]
I am using SST to simulate a Dragonfly network and I am trying to measure how much of each link is getting utilized compared to its available bandwidth. 
I couldn't find a method to get it from "stock" SST but I might have not looked in the right place, so I implemented my basic version of this by comparing the number of busy cycles for each port compared to the total cycles. 
This seems to work but not how I expected it to work. For example if I send just a small message (like 100Bytes) around, even with the various links set to having a 200Gbs bandwidth, I still get a very high utilization for stuff such as the global links which seems impossible.

Is my approach incorrect? And is there an already present tool to measure link utilization?

This is my code inside hr_router in the function hr_router::clock_handler
```
total_clock++;
for(int i = 0; i < num_ports; i++){ 
      if (i < this->topo->num_port_hosts) { // Just for some stats, doesn't matter for this case
          if(in_port_busy[i] > 0) {
              busy_clocks[i]++;
          }
      } else {
          if(out_port_busy[i] > 0) {
              busy_clocks[i]++;
          }
      }
  }
```

**Comment by feldergast** [comment]
There is a (currently indirect) way to get the active time of a link.  Right now, there is no way to measure the exact active time (that code is currently broken and I'm working on a fix).  Meanwhile, you can turn on the the following statistics in both routers and LinkControl: output_port_stalls and idle_time.  If you add those times together and subtract from total simulation time, you will get the active time on the corresponding link.  I'm tied up with some other work right now, but should have the actual active time stat fixed in the next month or so.

Just an FYI, the variables you were using in the code above are actually for the internal crossbar ports. You can also turn on xbar_stalls to see how often a port has data, but either didn't win arbitration or the output buffer the head packet was targeting didn't have enough credits (it doesn't differentiate between the two).
