### ISSUE TITLE
Question: Why does the memory controller convert GetSResp transactions to GetXResp?

### ISSUE THREAD

**Issue by sayandipde** [sstsimulator/sst-elements#1798]
Hello,
I am running a two prospero core cpu, with private L1, private L2 followed by dc and memory configured with MESI protocol. 
cpu0 trace: 2 r 10 16
cpu1 trace: 200 r 12 16

Why does the memory controller convert all GetSResp transactions to GetXResp? Because of this the directory controller (dc) always goes from IS->M state rather than IS->E state on a read. I am refering to this part of the code in memoryController.cc:

/* Read order matches execute order so that mis-ordering at backend can result in bad data */
if (resp->getCmd() == Command::GetSResp || (resp->getCmd() == Command::GetXResp && !noncacheable)) {
            readData(resp);
            if (!noncacheable) resp->setCmd(Command::GetXResp);
}
Please let me know the reason behind this design choice.

Thanks in advance.

Best regards,
Sayandip

**Comment by gvoskuilen** [comment]
The reason is that the more permissive GetXResp gives the directory/LLC/etc the option to make whatever permissions choice it wants when forwarding. The memory controller does not manage coherence states at all. As the directory doesn't store data, it doesn't have a concept of "dirty" or "clean", only owned (M) and shared (S). The use of 'M' for owned is a convenience because the state already existed in MemHierarchy, but you can interpret it as 'O'.
