### ISSUE TITLE
Firefly: Module load failed - pointers for debugging

### ISSUE THREAD

**Issue by saichennaintel** [sstsimulator/sst-elements#2287]
I'm currently trying to add nonblocking collectives into firefly. I have made some code modifications. While rebuilding firefly (using make all && make install), the build does not throw any errors however if I check the installation by running sst-info firefly. I get the following output:

![image](https://github.com/sstsimulator/sst-elements/assets/94569457/cb13c499-f035-42b6-ba99-51b8f823adfb)

As a result, while running a test configuration, it throws "No module named sst.firefly"
![image](https://github.com/sstsimulator/sst-elements/assets/94569457/03056e79-d13e-485a-a002-daf51276f3aa)
 
Any pointers on how to debug the issue? As it is not throwing any error during the build time, it makes it harder to find the root cause.

**Comment by feldergast** [comment]
The most likely cause of this is a missing symbol in the libfirefly library (for some reason, it's most often a destructor).  Since you are building a dynamically loaded library, the linker doesn't error on missing symbols, but the loading code in the core will fail if there is a symbol referenced that it can't resolve.  Unfortunately, as hard as we've tried, we haven't been able to get more specific error messages for this case.

**Comment by feldergast** [comment]
@saichennaintel Were you able to find the issue with loading?  If so, is it okay if we close this issue?

**Comment by saichennaintel** [comment]
You can close the ticket. I have put this work on hold currently. I'll follow your pointers on probable suspects while debugging on I resume the work.
