### ISSUE TITLE
Connecting one prefetcher to multiple memHierarchy.Cache components

### ISSUE THREAD

**Issue by jj16791** [sstsimulator/sst-elements#2420]
I'm looking to model a prefetcher layout seen in HPC hardware where, once a stream memory pattern has been detected, prefetch requests are sent to the L1D and L2D caches simultaneously. Is it possible to have one prefetch component connected to two memHierarchy.Cache components with the existing memHierarchy sst-element?

I've attempted to play around with the `createListeners` function but as far as I can tell, there may only suitable support for n prefetchers connecting to 1 cache and not 1 prefetcher connecting to n caches.

**Comment by gvoskuilen** [comment]
It's not possible to load a single SubComponent instance into two Components so you can't load one prefetcher into two caches. 

Two alternates that might work:
1. Model this using prefetchers that link directly to each other and coordinate prefetch requests. The prefetch subcomponents would have a link to each other. Since links have non-zero latency, if you want the prefetches issued in the same cycle, you will have to make sure to take the link latency into account.

2.  As we do with some MemBackends, you could create a shim CacheListener that has a link to a separate prefetch Component. The caches would all load the shim and you could connect the shims to the same prefetch component so they share. The prefetch Component could broadcast prefetches to the caches it is connected to.
