### ISSUE TITLE
Trac: #424 Packet size in trafficgen

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#37]
Packet size still not properly generated. 

1) in TrafficGen::buildGenerator at trafficgen.cc:171 

a Uniform dist with parameters range.first, range.second - 1 is created. There is no reason for this -1 to be here. 

From this results that to generate between [1,2] one need to configure with Min=0 and Max=3 

2) in UniformDist::UniformDist at trafficgen.h:141 

only max-min is used to determine the size of the interval. The offset is lost. So using a range [0, 400] is equivalent to using a range [1000, 1400]. The offset should also be given to SSTUniformDistribution 

3) getNextDouble in uniform.h is clearly sub-optimal and too complicated. An uniform can simply be obtained by multiplying the original random sample obtained from the random stream (Mersenne) by the interval size (and later adding the offset). There is no need for looping of any sort. 

4) A configuration with min > max should result in an error

**Comment by shavvn** [comment]
Regarding the *range.second - 1*, I think it makes sense, at least for some patterns, because in *pymerlin.py line 1028:*

```
_params["PacketDest:RangeMax"] = int(_params["num_peers"])
```

It is initialized as the number of peers. So if you don't "-1", it will probably result an out of range error and terminates the simulation, which happens to "HotSpot" when using dragonfly topology. Also if you build trafficgen without this "-1", dragonfly will also break for "Uniform" pattern.

I was gonna create a pull request for this issue but I figure it would be better to first discuss with you the concerns.
