### ISSUE TITLE
Pin tool path is not propogated correctly to Ariel code

### ISSUE THREAD

**Issue by amroawad2** [sstsimulator/sst-elements#468]
Pin tool path is not passed correctly

`1` Detailed description of problem or enhancement

After building sst-elements with pin, trying to run sst with an application causes a permission issue due to calling an incomplete path of pin.

`2` Describe how to reproduce

Building sst-elements with the following configuration command line:

./configure --with-sst-core=/home/aawad/SST_DEVE/BUILD --prefix=/home/aawad/SST_DEVE/BUILD_ELEMENTS/ --with-pin=/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux/

Then trying to run SST with executable generates the following error message:

> ArielComponent[arielcpu.cc:48:ArielCPU] Creating Ariel component...
> ArielComponent[arielcpu.cc:51:ArielCPU] Configuring for 8 cores...
> ArielComponent[arielcpu.cc:54:ArielCPU] Configuring for check addresses = no
> ArielComponent[arielcpu.cc:57:ArielCPU] Configuring for 1 memory levels.
> ArielComponent[arielcpu.cc:74:ArielCPU] Creating memory manager, default allocation from 0 memory pool.
> ArielComponent[arielcpu.cc:98:ArielCPU] Memory manager construction is completed.
> ArielComponent[arielcpu.cc:129:ArielCPU] Model specifies that there are 0 application arguments
> ArielComponent[arielcpu.cc:139:ArielCPU] Interception and instrumentation of multi-level memory calls is ENABLED.
> ArielComponent[arielcpu.cc:144:ArielCPU] Tracking the stack and dumping on malloc calls is DISABLED.
> ArielComponent[arielcpu.cc:149:ArielCPU] Base pipe name: /sst_shmem_10439-0-1681692777
> ArielComponent[arielcpu.cc:160:ArielCPU] Processing application arguments...
> ArielComponent[arielcpu.cc:263:ArielCPU] Completed processing application arguments.
> ArielComponent[arielcpu.cc:270:ArielCPU] Creating core to cache links...
> ArielComponent[arielcpu.cc:280:ArielCPU] Creating processor cores and cache links...
> ArielComponent[arielcpu.cc:283:ArielCPU] Configuring cores and cache links...
> ArielComponent[arielcpu.cc:307:ArielCPU] Registering ArielCPU clock at 2660MHz
> ArielComponent[arielcpu.cc:311:ArielCPU] Clocks registered.
> ArielComponent[arielcpu.cc:319:ArielCPU] Completed initialization of the Ariel CPU.
> ArielComponent[arielcpu.cc:327:init] Launching PIN...
> ArielComponent[arielcpu.cc:438:forkPINChild] Launching executable: /usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux...
> execve: Permission denied
> ArielComponent[arielcpu.cc:458:forkPINChild] Call to execvp returned: -1
> FATAL: ArielComponent[arielcpu.cc:461:forkPINChild] Error executing: /usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux under a PIN fork
> FATAL: ArielComponent[arielcpu.cc:461:forkPINChild] Error executing: /usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux under a PIN fork

`3` What Operating system(s) and versions 

RHE7

`4` What version of external libraries (Boost, MPI)

boost-1.56.0

Note: a temporary fix is to add the following to the Ariel parameters:
"launcher" : "/usr/local/module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux//pin.sh"

**Comment by hughes-c** [comment]
This is a problem with the way the path is passed through using pairs of quotes:
`-DPINTOOL_EXECUTABLE=""/usr/local//module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux//pin.sh""`
--> `/usr/local`

The shell strips off the outer quotes but then something wonky happens with the extra / and everything following it is stripped off as well. The same thing happens if only single or double quotes are used. If the outer quotes are replaced with a single quote or escaped, then the inner pair of quotes are preserved:
`-DPINTOOL_EXECUTABLE='"/usr/local//module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux//pin.sh"'`
--> `"/usr/local//module-pkgs/pin/pin-2.14-71313-gcc.4.4.7-linux//pin.sh"`

That means that you can treat the PINTOOL_EXECUTABLE macro as a string without having to pass it through the additional stringize macro.
