### ISSUE TITLE
Ariel cores not full utilized

### ISSUE THREAD

**Issue by yeungsl** [sstsimulator/sst-elements#688]
New Issue for sst-elements
--------------------------

I ran a couple of executable on the same configuration where Ariel is used as CPU with 8 cores by default and with l1, l2 caches linked through memBus. However, when I print all the Statistics, it seems to me that only one of cores and its corresponding caches has done the work, because the statistics from other cores and caches are all 0; the executable exits correctly and the simulation ends correctly. Is there any apparent mistake that I am making?

**Comment by nmhamster** [comment]
HI @yeungsl, are you running a multi-threaded code?

**Comment by yeungsl** [comment]
NO I don't think so

**Comment by nmhamster** [comment]
@yeungsl - if you aren't running a threaded binary then the other cores will all return zero for their counters because there is no work to be done on them. We detect the presence of threads running in the binary and map these onto the cores for you, if you only have one thread then only one core will do any work (and have any counters above zero). Let us know if you want a more detailed explanation.

**Comment by yeungsl** [comment]
Thanks @nmhamster, glad to confirm what I originally thought.

**Comment by nmhamster** [comment]
I'll close this issue, please let us know if you have any other questions.
