### ISSUE TITLE
MemSieve has Inconsistent Output with Threaded PDES Core 

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#80]
Wide variation is time output for MemSieve runs when using Threaded PDES Core

**Comment by jpvandy** [comment]
Not sure the variation is that wide, but . . .
The simulation time is reported as "5.5 ns", for both n=1 and n=2.
The n=1 table is

sieve, histogram_reads, , Histogram, 5501, 0, 0, 24575, 4096, 6, 16395, 268468325, 2, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0
sieve, histogram_writes, , Histogram, 5501, 0, 0, 24575, 4096, 6, 12267, 83534309, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0

and the n=2 table is 

sieve, histogram_reads, , Histogram, 6000, 0, 0, 24575, 4096, 6, 16395, 268468325, 2, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0
sieve, histogram_writes, , Histogram, 6000, 0, 0, 24575, 4096, 6, 12267, 83534309, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0

The only thing different is the number of pico seconds reported.

**Comment by bjmoor** [comment]
This would currently be expected.  You *should* see the same thing if you run with two MPI processes.  It has to do with synchronization times between event queue.   I believe @feldergast had some ideas about how to get the Statistics objects to get "real" finish time, rather than "next sync" finish time.

**Comment by jwilso** [comment]
@gvoskuilen  to confirm closure of this issue.

**Comment by nmhamster** [comment]
This is expected due to parallel synchronization behavior. Issue closed.
